### ISSUE TITLE
lilypond svg improvements

### ISSUE THREAD

**Issue by sertansenturk** [hsercanatli/makam-musicxml2lilypond#8]
Using the svg's generated from lilypond is beneficial because 1) we can render the notes individually, 2) the beamings are correct.
- [x] Although the key signature is set, lilypond renders the accidentals in measures. During lilypond generation, the accidental of a note which is in the key signature should be hidden.
- [x] The arrangement of the key signatures (which key signature should be the first, the second, the third etc...)

Additional but not necessary to Dunya
- [x] The fonts of the sectoin names are inconsistent
- [x] Print title, composer, makam and usul information of related score

Below are the SymbTr pdf and the pdf rendered by Lilypond:
[lilypond.pdf](https://github.com/MTG/dunya/files/12502/tmphtSWzv.pdf)
[evcara--sazsemaisi--aksaksemai----dilhayat_kalfa.pdf](https://github.com/MTG/dunya/files/12509/evcara--sazsemaisi--aksaksemai----dilhayat_kalfa.pdf)

(github doesn't allow svg, but pdf and svg looks identical)

**Comment by sertansenturk** [comment]
The notes with accidentals which are not part of the key signatures are rendered with both the correct accidental but also with a natural sign.

http://dunya.compmusic.upf.edu/makam/recording/dfc16e22-0aae-4bd0-a32c-5c000130e96a

In the 9th messure, the b note in the end. (0:20)

**Comment by hsercanatli** [comment]
The arrangement of the key signatures is better now but not perfect for makams like Şedarabân.

The accidental in b note is different than the key signatures ("http://dunya.compmusic.upf.edu/makam/recording/dfc16e22-0aae-4bd0-a32c-5c000130e96a"). Lilypond shows the accidentals, which are added to the notes part of key signatures, in this way. First it puts a natural, then adds the accidental. I couldn't solve it for now.
